input_directory: "P://Internship//Transcription//input_videos"
output_audio_directory: "P://Internship//Transcription//output_audio"
output_transcripts_directory: "P://Internship//Transcription//output_transcripts"
batch_size: 10
cooling_period: 6  # seconds
max_workers: 4
gpu: false
logging:
  level: "INFO"
  directory: "logs"  # Folder for logs
  file: "transcription.log"
